services:
  server:
    build:
      context: ./apps/server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./apps/server/.env
    volumes:
      - ./apps/server:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "pnpx prisma generate && pnpm start:dev"
    networks:
      - app-network

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/web:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm dev -- --host
    networks:
      - app-network

networks:
  app-network:
    driver: bridge